---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-migration.html 
summary: Esta seção fornece detalhes sobre os fatores a serem considerados ao migrar o banco de dados Oracle do local para a instância AWS EC2 e armazenamento FSx. 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= Migração de banco de dados local para nuvem pública
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A migração de banco de dados é uma tarefa desafiadora em qualquer sentido.  Migrar um banco de dados Oracle do local para a nuvem não é exceção.

As seções a seguir fornecem os principais fatores a serem considerados ao migrar bancos de dados Oracle para a nuvem pública da AWS com a plataforma de computação AWS EC2 e armazenamento FSx.



== O armazenamento ONTAP está disponível no local

Se o banco de dados Oracle local estiver em um array de armazenamento ONTAP , será mais fácil configurar a replicação para migração de banco de dados usando a tecnologia NetApp SnapMirror , integrada ao armazenamento ONTAP do AWS FSx.  O processo de migração pode ser orquestrado usando o console NetApp BlueXP .

. Crie uma instância do EC2 de computação de destino que corresponda à instância local.
. Provisione volumes de banco de dados correspondentes e de tamanho igual no console FSx.
. Monte os volumes do banco de dados FSx na instância EC2.
. Configure a replicação do SnapMirror entre os volumes do banco de dados local para os volumes do banco de dados FSx de destino.  A sincronização inicial pode levar algum tempo para mover os dados de origem primários, mas quaisquer atualizações incrementais subsequentes são muito mais rápidas.
. No momento da troca, encerre o aplicativo principal para interromper todas as transações.  Na interface CLI do Oracle sqlplus, execute uma alternância de log on-line do Oracle e permita que a sincronização do SnapMirror envie o último log arquivado para o volume de destino.
. Divida os volumes espelhados, execute a recuperação do Oracle no destino e coloque o banco de dados em serviço.
. Aponte aplicativos para o banco de dados Oracle na nuvem.


O vídeo a seguir demonstra como migrar um banco de dados Oracle local para o AWS FSx/EC2 usando o console NetApp BlueXP e a replicação do SnapMirror .

.Migrar banco de dados Oracle local para AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== O armazenamento ONTAP não está disponível no local

Se o banco de dados Oracle local estiver hospedado em um armazenamento de terceiros diferente do ONTAP, a migração do banco de dados será baseada na restauração de uma cópia de backup do banco de dados Oracle.  Você deve reproduzir o log de arquivo para torná-lo atual antes de alternar.

O AWS S3 pode ser usado como uma área de armazenamento temporário para movimentação e migração de banco de dados.  Veja as seguintes etapas de alto nível para este método:

. Provisione uma nova instância do EC2 correspondente que seja comparável à instância local.
. Provisione volumes de banco de dados iguais do armazenamento FSx e monte os volumes na instância do EC2.
. Crie uma cópia de backup do Oracle em nível de disco.
. Mova a cópia de backup para o armazenamento AWS S3.
. Recrie o arquivo de controle do Oracle e restaure e recupere o banco de dados extraindo dados e o log de arquivamento do armazenamento S3.
. Sincronize o banco de dados Oracle de destino com o banco de dados de origem local.
. Na troca, encerre o aplicativo e o banco de dados Oracle de origem.  Copie os últimos logs de arquivo e aplique-os ao banco de dados Oracle de destino para atualizá-lo.
. Inicie o banco de dados de destino para acesso do usuário.
. Redirecione o aplicativo para o banco de dados de destino para concluir a troca.




== Migrar bancos de dados Oracle locais para AWS FSx/EC2 usando a realocação de PDB com disponibilidade máxima

Essa abordagem de migração é mais adequada para bancos de dados Oracle que já estão implantados no modelo multilocatário PDB/CDB, e o armazenamento ONTAP não está disponível no local.  O método de realocação de PDB utiliza a tecnologia de clonagem dinâmica do Oracle PDB para mover PDBs entre um CDB de origem e um CDB de destino, minimizando a interrupção do serviço.

Primeiro, crie um CDB no AWS FSx/EC2 com armazenamento suficiente para hospedar PDBs a serem migrados do local.  Vários PDBs locais podem ser realocados um por vez.

. Se o banco de dados local for implantado em uma única instância em vez do modelo PDB/CDB multilocatário, siga as instruções emlink:azure-ora-nfile-migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["Convertendo uma única instância não-CDB em um PDB em um CDB multilocatário"^] para converter a instância única em PDB/CDB multilocatário.  Em seguida, siga a próxima etapa para migrar o PDB convertido para CDB no AWS FSx/EC2.
. Se o banco de dados local já estiver implantado no modelo PDB/CDB multilocatário, siga as instruções emlink:azure-ora-nfile-migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["Migrar bancos de dados Oracle locais para a nuvem com realocação de PDB"^] para executar a migração.


O vídeo a seguir demonstra como um banco de dados Oracle (PDB) pode ser migrado para o FSx/EC2 usando a realocação de PDB com disponibilidade máxima.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["Migrar Oracle PDB local para AWS CDB com disponibilidade máxima"^]


NOTE: Embora as instruções nas etapas 1 e 2 sejam ilustradas no contexto da nuvem pública do Azure, os procedimentos são aplicáveis à nuvem AWS sem nenhuma alteração.

A equipe de automação de soluções da NetApp fornece um kit de ferramentas de migração que pode facilitar a migração do banco de dados Oracle do local para a nuvem da AWS.  Use o comando a seguir para baixar o kit de ferramentas de migração do banco de dados Oracle para realocação do PDB.

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----