---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-deploy-intro.html 
summary: Este white paper fornece um esboço e validação de uma solução para HA e DR de banco de dados Oracle RDS personalizado pela AWS, aproveitando o serviço de armazenamento AWS FSx em uma implantação de múltiplas zonas de disponibilidade. 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357: Introdução às melhores práticas de implantação do Oracle Database no EC2 e FSx
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, Jeffrey Steiner, NetApp

[role="lead"]
Muitos bancos de dados Oracle empresariais de missão crítica ainda são hospedados no local, e muitas empresas estão procurando migrar esses bancos de dados Oracle para uma nuvem pública.  Frequentemente, esses bancos de dados Oracle são centrados em aplicativos e, portanto, exigem configurações específicas do usuário, um recurso que está ausente em muitas ofertas de nuvem pública de banco de dados como serviço.  Portanto, o cenário atual de banco de dados exige uma solução de banco de dados Oracle baseada em nuvem pública, construída a partir de um serviço de computação e armazenamento escalável e de alto desempenho que possa acomodar requisitos exclusivos.  As instâncias de computação do AWS EC2 e o serviço de armazenamento AWS FSx podem ser as peças que faltam nesse quebra-cabeça que você pode aproveitar para criar e migrar suas cargas de trabalho de banco de dados Oracle de missão crítica para uma nuvem pública.

O Amazon Elastic Compute Cloud (Amazon EC2) é um serviço web que fornece capacidade de computação segura e redimensionável na nuvem.  Ele foi projetado para facilitar a computação em nuvem em escala web para empresas.  A interface simples do serviço web do Amazon EC2 permite que você obtenha e configure capacidade com o mínimo de atrito.  Ele fornece controle total dos seus recursos de computação e permite que você trabalhe no ambiente de computação comprovado da Amazon.

O Amazon FSx ONTAP é um serviço de armazenamento da AWS que usa o armazenamento de blocos e arquivos NetApp ONTAP líder do setor, que expõe NFS, SMB e iSCSI.  Com um mecanismo de armazenamento tão poderoso, nunca foi tão fácil realocar aplicativos de banco de dados Oracle de missão crítica para a AWS com tempos de resposta abaixo de um milissegundo, vários GBps de taxa de transferência e mais de 100.000 IOPS por instância de banco de dados.  Melhor ainda, o serviço de armazenamento FSx vem com capacidade de replicação nativa que permite que você migre facilmente seu banco de dados Oracle local para a AWS ou replique seu banco de dados Oracle de missão crítica para uma zona de disponibilidade secundária da AWS para HA ou DR.

O objetivo desta documentação é fornecer processos passo a passo, procedimentos e orientações de práticas recomendadas sobre como implantar e configurar um banco de dados Oracle com armazenamento FSx e uma instância EC2 que oferece desempenho semelhante a um sistema local.  A NetApp também fornece um kit de ferramentas de automação que automatiza a maioria das tarefas necessárias para a implantação, configuração e gerenciamento da carga de trabalho do seu banco de dados Oracle na nuvem pública da AWS.

Para saber mais sobre a solução e o caso de uso, assista ao seguinte vídeo de visão geral:

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["Modernize seu banco de dados Oracle com nuvem híbrida na AWS e FSx ONTAP, Parte 1 - Caso de uso e arquitetura de solução"^]
