---
sidebar: sidebar 
permalink: oracle/azure-ora-nfile-usecase.html 
summary: Este guia de práticas recomendadas fornece detalhes de uma solução para implantar e migrar o banco de dados Oracle no armazenamento de arquivos do Azure NetApp e na VM do Azure. 
keywords: database, Oracle, Azure NetApp files, Azure 
---
= TR-4954: Melhores práticas de implantação e migração do Oracle Database para ANF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este guia de práticas recomendadas fornece detalhes de uma solução para implantar e migrar o banco de dados Oracle no armazenamento de arquivos do Azure NetApp e na VM do Azure.



== Visão geral

Muitos bancos de dados empresariais Oracle de missão crítica ainda são hospedados no local, e muitas empresas estão procurando migrar esses bancos de dados Oracle para uma nuvem pública.  Frequentemente, esses bancos de dados Oracle são centrados em aplicativos e, portanto, exigem configurações específicas do usuário, um recurso que está ausente em muitas ofertas de nuvem pública de banco de dados como serviço.  Portanto, o cenário atual de banco de dados exige uma solução de banco de dados Oracle baseada em nuvem pública, construída a partir de um serviço de computação e armazenamento escalável e de alto desempenho que possa acomodar requisitos exclusivos.  As instâncias de computação da máquina virtual do Azure e o serviço de armazenamento do Azure NetApp Files podem ser as peças que faltam nesse quebra-cabeça que você pode aproveitar para criar e migrar suas cargas de trabalho de banco de dados Oracle de missão crítica para uma nuvem pública.



== Máquina Virtual do Azure

As máquinas virtuais do Azure são um dos vários tipos de recursos de computação escaláveis e sob demanda que o Azure oferece.  Normalmente, você escolhe uma máquina virtual quando precisa de mais controle sobre o ambiente de computação do que as outras opções oferecem.  As máquinas virtuais do Azure oferecem uma maneira rápida e fácil de criar um computador com configurações específicas necessárias para executar seu banco de dados Oracle, seja para cargas de trabalho com uso intensivo de computação ou memória.  Máquinas virtuais em uma rede virtual do Azure podem ser facilmente conectadas à rede da sua organização, por exemplo, por meio de um túnel VPN seguro.



== Azure NetApp Files (ANF)

O Azure NetApp Files é um serviço totalmente gerenciado da Microsoft que levará sua carga de trabalho de banco de dados para a nuvem com mais rapidez e segurança do que nunca.  Ele foi projetado para atender aos principais requisitos de execução de cargas de trabalho de alto desempenho, como bancos de dados Oracle na nuvem, e fornece níveis de desempenho que refletem a gama real de demandas de IOPS, baixa latência, alta disponibilidade, alta durabilidade, capacidade de gerenciamento em escala e backup, recuperação e clonagem rápidos e eficientes.  Esses recursos são possíveis porque o Azure NetApp Files é baseado em sistemas NetApp ONTAP físicos all-flash executados no ambiente de data center do Azure.  O Azure NetApp Files é completamente integrado aos DCs e ao portal do Azure, e os clientes podem usar a mesma interface gráfica confortável e APIs para criar e gerenciar arquivos compartilhados como qualquer outro objeto do Azure.  Com o arquivo Azure NetApp , você pode desbloquear todos os recursos do Azure sem riscos, custos ou tempo extras e confiar no único serviço de arquivo empresarial nativo do Azure.



== Conclusão

Esta documentação descreve em detalhes como implantar, configurar e migrar um banco de dados Oracle com uma máquina virtual do Azure e um serviço de armazenamento do Azure NetApp Files que oferece desempenho e durabilidade semelhantes a um sistema local.  Para obter orientações sobre as melhores práticas, consulte TR-4780link:https://www.netapp.com/media/17105-tr4780.pdf["Bancos de dados Oracle no Microsoft Azure"^] .  Mais importante ainda, a NetApp também fornece kits de ferramentas de automação que automatizam a maioria das tarefas necessárias para a implantação, configuração, proteção de dados, migração e gerenciamento da carga de trabalho do seu banco de dados Oracle na nuvem pública do Azure.  Os kits de ferramentas de automação estão disponíveis para download no site público do GitHub da NetApp :link:https://github.com/NetApp-Automation/["NetApp- Automação"^] .
