---
sidebar: sidebar 
permalink: oracle/gcnv-oracle-primary-database.html 
keywords: oracle database, dbca, asm, cdb, pdb, oracle restart, srvctl, oracle 26ai, primary database 
summary: Crie o banco de dados primário do Oracle no armazenamento iSCSI do Google Cloud NetApp Volumes usando o Assistente de Configuração do Banco de Dados Oracle no modo silencioso. Este procedimento abrange a execução do dbca para criar o banco de dados de contêiner e o banco de dados plugável em grupos de discos ASM com suporte do GCNV, configurar destinos de log de arquivamento e adicionar um serviço de aplicativo baseado em funções para failover transparente. 
---
= Crie o banco de dados primário do Oracle no Google Cloud NetApp Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Crie o banco de dados primário do Oracle no armazenamento iSCSI do Google Cloud NetApp Volumes usando o Assistente de Configuração do Banco de Dados Oracle no modo silencioso. Este procedimento abrange executar  `dbca` para criar o banco de dados de contêiner e o banco de dados plugável em grupos de discos ASM com suporte do GCNV, configurar os destinos de log de arquivamento e adicionar um serviço de aplicativo baseado em funções para failover transparente após a ativação do Data Guard.

[[create-primary-database]]
.Passos
Crie o banco de dados de contêiner Oracle e o banco de dados plugável em  `oracdb1` usando  `dbca` no modo silencioso, configure os destinos de log de arquivamento, verifique o registro do Oracle Restart e adicione um serviço de aplicativo baseado em funções para failover transparente do cliente.

. Execute  `dbca` em modo silencioso para criar o CDB e o PDB nos grupos de discos ASM:
+
[source, bash]
----
sudo -u oracle bash -c '
export ORACLE_HOME=/u01/app/oracle/product/26ai/db_1
export PATH=$ORACLE_HOME/bin:$PATH

dbca -silent -createDatabase \
  -templateName General_Purpose.dbc \
  -gdbname orcl -sid orcl \
  -characterSet AL32UTF8 -nationalCharacterSet AL16UTF16 \
  -sysPassword "ChangeMe!1" -systemPassword "ChangeMe!1" \
  -emConfiguration NONE \
  -datafileDestination +DATA -storageType ASM \
  -recoveryAreaDestination +FRA -recoveryAreaSize 25000 \
  -enableArchive true -archiveLogMode AUTO \
  -memoryMgmtType AUTO_SGA -totalMemory 4096 \
  -databaseType MULTIPURPOSE \
  -createAsContainerDatabase true -numberOfPDBs 1 \
  -pdbName orclpdb -pdbAdminPassword "ChangeMe!1" \
  -ignorePreReqs
'
----
. Aponte os logs de arquivamento para  `+RECO` e abra e salve o estado do banco de dados plugável. O standby usa configurações de log de arquivamento correspondentes em xref:gcnv-oracle-standby-database.adoc#standby-init-ora-and-nomount[Etapa 2: Standby init.ora, pfile e NOMOUNT]:
+
[source, bash]
----
sudo -u oracle bash -c '
export ORACLE_HOME=/u01/app/oracle/product/26ai/db_1
export ORACLE_SID=orcl
$ORACLE_HOME/bin/sqlplus -s / as sysdba <<SQL
ALTER SYSTEM SET log_archive_dest_1='\''LOCATION=+RECO VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=orcl'\'' SCOPE=BOTH;
ALTER PLUGGABLE DATABASE ALL OPEN;
ALTER PLUGGABLE DATABASE ALL SAVE STATE;
EXIT
SQL
'
----
. Verifique se o banco de dados está em execução no Oracle Restart:
+
[source, bash]
----
sudo /u01/app/26ai/grid/bin/srvctl status database -d orcl
# Expected: Database is running

sudo -u oracle sqlplus -s / as sysdba <<<"SELECT name, open_mode, log_mode FROM v\$database;"
# Expected: ORCL, READ WRITE, ARCHIVELOG
----
. Crie um serviço de aplicativo baseado em funções para que os aplicativos se conectem via `orclapp` e o failover seja transparente quando o Data Guard estiver ativado:
+
[source, bash]
----
sudo -u oracle bash -c '
export GRID_HOME=/u01/app/26ai/grid
export ORACLE_HOME=/u01/app/oracle/product/26ai/db_1
export PATH=$ORACLE_HOME/bin:$GRID_HOME/bin:$PATH

srvctl add service \
  -db orcl \
  -service orclapp \
  -pdb orclpdb \
  -role PRIMARY \
  -policy AUTOMATIC

srvctl start service -db orcl -service orclapp
srvctl status service -db orcl -service orclapp
'
----
+
Após a ativação do Data Guard Broker,  `orclapp` é executado somente no PRIMARY. Multiplexe os arquivos de controle entre os grupos de discos ASM e dimensione a memória de acordo com a carga de trabalho.





[[whats-next]]
== Qual é o próximo passo?

Para configurar a proteção em espera e a prontidão para failover, acesse xref:gcnv-oracle-standby-database.adoc[Crie o banco de dados standby do Oracle] em  `oracdb2`.
