---
sidebar: sidebar 
permalink: dbops/hybrid-dbops-sc-prereq-cloud.html 
summary: Antes de instalar o conector Cloud Manager e o Cloud Volumes ONTAP e configurar o SnapMirror, precisamos realizar alguma preparação para nosso ambiente de nuvem.  Esta página descreve o trabalho que precisa ser feito, bem como as considerações ao implantar o Cloud Volumes ONTAP. 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= Pré-requisitos para a nuvem pública
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de instalar o conector Cloud Manager e o Cloud Volumes ONTAP e configurar o SnapMirror, precisamos realizar alguma preparação para nosso ambiente de nuvem.  Esta página descreve o trabalho que precisa ser feito, bem como as considerações ao implantar o Cloud Volumes ONTAP.



== Lista de verificação de pré-requisitos para implantação do Cloud Manager e do Cloud Volumes ONTAP

* Um login do NetApp Cloud Central
* Acesso à rede a partir de um navegador da web para vários terminais
* Um local de rede para um conector
* Permissões do provedor de nuvem
* Networking para serviços individuais


Para obter mais informações sobre o que você precisa para começar, visite nosso https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["documentação da nuvem"^] .



== Considerações



=== 1. O que é um conector do Cloud Manager?

Na maioria dos casos, um administrador de conta do Cloud Central deve implantar um conector na sua rede local ou na nuvem.  O conector permite que o Cloud Manager gerencie recursos e processos dentro do seu ambiente de nuvem pública.

Para mais informações sobre Conectores, visite nosso https://docs.netapp.com/us-en/occm/concept_connectors.html["documentação da nuvem"^] .



=== 2. Dimensionamento e arquitetura do Cloud Volumes ONTAP

Ao implantar o Cloud Volumes ONTAP, você pode escolher entre um pacote predefinido ou a criação de sua própria configuração.  Embora muitos desses valores possam ser alterados posteriormente sem interrupções, há algumas decisões importantes que precisam ser tomadas antes da implantação com base nas cargas de trabalho a serem implantadas na nuvem.

Cada provedor de nuvem tem diferentes opções de implantação e quase toda carga de trabalho tem suas próprias propriedades exclusivas.  A NetApp tem uma https://bluexp.netapp.com/calculator-hub["Calculadora de TCO"^] que pode ajudar a dimensionar implantações corretamente com base na capacidade e no desempenho, mas foi criado em torno de alguns conceitos básicos que valem a pena considerar:

* Capacidade necessária
* Capacidade de rede da máquina virtual em nuvem
* Características de desempenho do armazenamento em nuvem


O segredo é planejar uma configuração que não apenas satisfaça os requisitos atuais de capacidade e desempenho, mas também considere o crescimento futuro.  Isso é geralmente conhecido como capacidade de sobra e desempenho de sobra.

Se desejar mais informações, leia a documentação sobre o planejamento correto para https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^] , https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azul"^] , e https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^] .



=== 3. Nó único ou alta disponibilidade?

Em todas as nuvens, há a opção de implantar o CVO em um único nó ou em um par de alta disponibilidade em cluster com dois nós.  Dependendo do caso de uso, você pode querer implantar um único nó para economizar custos ou um par de HA para fornecer mais disponibilidade e redundância.

Para um caso de uso de DR ou para criar armazenamento temporário para desenvolvimento e teste, nós únicos são comuns, pois o impacto de uma interrupção repentina de zona ou infraestrutura é menor.  No entanto, para qualquer caso de uso de produção, quando os dados estão em apenas um local ou quando o conjunto de dados precisa ter mais redundância e disponibilidade, a alta disponibilidade é recomendada.

Para obter mais informações sobre a arquitetura da versão de alta disponibilidade de cada nuvem, visite a documentação para https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^] , https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azul"^] e https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^] .
