---
sidebar: sidebar 
permalink: automation/cli-automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: Esta página descreve o método automatizado para implantar o Oracle19c no armazenamento NetApp ONTAP . 
---
= Procedimento de implantação passo a passo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento detalha a implantação do Oracle 19c usando a interface de linha de comando de automação (CLI).



== Implantação CLI do banco de dados Oracle 19c

Esta seção aborda as etapas necessárias para preparar e implantar o Oracle19c Database com a CLI.  Certifique-se de ter revisado olink:getting-started-requirements.html["Seção de Introdução e Requisitos"] e preparou seu ambiente adequadamente.



=== Baixar repositório Oracle19c

. No seu controlador ansible, execute o seguinte comando:
+
[source, cli]
----
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git
----
. Após baixar o repositório, altere os diretórios para na_oracle19c_deploy <cd na_oracle19c_deploy>.




=== Editar o arquivo hosts

Conclua o seguinte antes da implantação:

. Edite o arquivo hosts no diretório na_oracle19c_deploy.
. Em [ontap], altere o endereço IP para o IP de gerenciamento do cluster.
. No grupo [oracle], adicione os nomes dos hosts Oracle.  O nome do host deve ser resolvido para seu endereço IP por meio de DNS ou do arquivo hosts, ou deve ser especificado no host.
. Depois de concluir essas etapas, salve as alterações.


O exemplo a seguir descreve um arquivo host:

[source, shell]
----
#ONTAP Host

[ontap]

"10.61.184.183"

#Oracle hosts

[oracle]

"rtpora01"

"rtpora02"
----
Este exemplo executa o manual e implanta o Oracle 19c em dois servidores Oracle DB simultaneamente.  Você também pode testar com apenas um servidor de banco de dados.  Nesse caso, você só precisa configurar um arquivo de variável de host.


NOTE: O manual é executado da mesma maneira, independentemente de quantos hosts e bancos de dados Oracle você implanta.



=== Edite o arquivo host_name.yml em host_vars

Cada host Oracle tem seu arquivo de variáveis de host identificado pelo seu nome de host que contém variáveis específicas do host.  Você pode especificar qualquer nome para seu host.  Edite e copie o `host_vars` da seção Host VARS Config e cole-o no local desejado `host_name.yml` arquivo.


NOTE: Os itens em azul devem ser alterados para combinar com seu ambiente.



=== Configuração do VARS do host

[source, shell]
----
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Add your Oracle Host
ansible_host: "10.61.180.15"

# Oracle db log archive mode: true - ARCHIVELOG or false - NOARCHIVELOG
log_archive_mode: "true"

# Number of pluggable databases per container instance identified by sid. Pdb_name specifies the prefix for container database naming in this case cdb2_pdb1, cdb2_pdb2, cdb2_pdb3
oracle_sid: "cdb2"
pdb_num: "3"
pdb_name: "{{ oracle_sid }}_pdb"

# CDB listener port, use different listener port for additional CDB on same host
listener_port: "1523"

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: "5464"

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them black if em express is not installed.
em_configuration: "DBEXPRESS"
em_express_port: "5501"

# {{groups.oracle[0]}} represents first Oracle DB server as defined in Oracle hosts group [oracle]. For concurrent multiple Oracle DB servers deployment, [0] will be incremented for each additional DB server. For example,  {{groups.oracle[1]}}" represents DB server 2, "{{groups.oracle[2]}}" represents DB server 3 ... As a good practice and the default, minimum three volumes is allocated to a DB server with corresponding /u01, /u02, /u03 mount points, which store oracle binary, oracle data, and oracle recovery files respectively. Additional volumes can be added by click on "More NFS volumes" but the number of volumes allocated to a DB server must match with what is defined in global vars file by volumes_nfs parameter, which dictates how many volumes are to be created for each DB server.
host_datastores_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
----


=== Edite o arquivo vars.yml

O `vars.yml` O arquivo consolida todas as variáveis específicas do ambiente (ONTAP, Linux ou Oracle) para implantação do Oracle.

. Edite e copie as variáveis da seção VARS e cole essas variáveis em seu `vars.yml` arquivo.


[source, shell]
----
#######################################################################
###### Oracle 19c deployment global user configuration variables ######
######  Consolidate all variables from ontap, linux and oracle   ######
#######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the ONTAP Cluster
nodes:
 - "AFF-01"
 - "AFF-02"

#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: "203", name: "infra_NFS", protocol: "NFS"}
More Storage VLANsEnter Storage VLANs details

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: "aggr01_node01"}
  - {aggr_name: "aggr01_node02"}

#SVM name
svm_name: "ora_svm"

# SVM Management LIF Details
svm_mgmt_details:
  - {address: "172.21.91.100", netmask: "255.255.255.0", home_port: "e0M"}

# NFS storage parameters when data_protocol set to NFS. Volume named after Oracle hosts name identified by mount point as follow for oracle DB server 1. Each mount point dedicates to a particular Oracle files: u01 - Oracle binary, u02 - Oracle data, u03 - Oracle redo. Add additional volumes by click on "More NFS volumes" and also add the volumes list to corresponding host_vars as host_datastores_nfs variable. For multiple DB server deployment, additional volumes sets needs to be added for additional DB server. Input variable "{{groups.oracle[1]}}_u01", "{{groups.oracle[1]}}_u02", and "{{groups.oracle[1]}}_u03" as vol_name for second DB server. Place volumes for multiple DB servers alternatingly between controllers for balanced IO performance, e.g. DB server 1 on controller node1, DB server 2 on controller node2 etc. Make sure match lif address with controller node.

volumes_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}

#NFS LIFs IP address and netmask

nfs_lifs_details:
  - address: "172.21.94.200" #for node-1
    netmask: "255.255.255.0"
  - address: "172.21.94.201" #for node-2
    netmask: "255.255.255.0"

#NFS client match

client_match: "172.21.94.0/24"

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes

mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.

hugepages_nr: "1234"

# RedHat subscription username and password

redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: "your.domain.com"

# Set initial password for all required Oracle passwords. Change them after installation.

initial_pwd_all: "netapp123"
----


=== Execute o manual

Após concluir os pré-requisitos ambientais necessários e copiar as variáveis para `vars.yml` e `your_host.yml` , agora você está pronto para implantar os playbooks.


NOTE: <nome de usuário> deve ser alterado para corresponder ao seu ambiente.

. Execute o manual do ONTAP passando as tags corretas e o nome de usuário do cluster ONTAP .  Preencha a senha para o cluster ONTAP e vsadmin quando solicitado.
+
[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml
----
. Execute o playbook do Linux para executar a parte do Linux da implantação.  Entrada para senha de administrador ssh e também senha de sudo.
+
[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml
----
. Execute o playbook do Oracle para executar a parte do Oracle da implantação.  Entrada para senha de administrador ssh e também senha de sudo.
+
[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml
----




=== Implantar banco de dados adicional no mesmo host Oracle

A parte Oracle do manual cria um único banco de dados de contêiner Oracle em um servidor Oracle por execução.  Para criar um banco de dados de contêiner adicional no mesmo servidor, conclua as seguintes etapas:

. Revise as variáveis host_vars.
+
.. Volte para a etapa 3 - Edite o `host_name.yml` arquivar em `host_vars` .
.. Altere o Oracle SID para uma sequência de nomenclatura diferente.
.. Altere a porta do ouvinte para um número diferente.
.. Altere a porta do EM Express para um número diferente se você tiver instalado o EM Express.
.. Copie e cole as variáveis de host revisadas no arquivo de variáveis de host Oracle em `host_vars` .


. Execute o manual com o `oracle_config` etiqueta como mostrado acima em<<Execute o manual>> .




=== Validar instalação do Oracle

. Efetue login no servidor Oracle como usuário oracle e execute os seguintes comandos:
+
[source, cli]
----
ps -ef | grep ora
----
+

NOTE: Isso listará os processos do Oracle se a instalação for concluída conforme o esperado e o Oracle DB for iniciado

. Efetue login no banco de dados para verificar as configurações do banco de dados e os PDBs criados com os seguintes conjuntos de comandos.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL>

SQL> select name, log_mode from v$database;
NAME      LOG_MODE
--------- ------------
CDB2      ARCHIVELOG

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO

col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;

SQL> col svrname form a30
SQL> col dirname form a30
SQL> select svrname, dirname, nfsversion from v$dnfs_servers;

SVRNAME                        DIRNAME                        NFSVERSION
------------------------------ ------------------------------ ----------------
172.21.126.200                 /rhelora03_u02                 NFSv3.0
172.21.126.200                 /rhelora03_u03                 NFSv3.0
172.21.126.200                 /rhelora03_u01                 NFSv3.0
----
+
Isso confirma que o dNFS está funcionando corretamente.

. Conecte-se ao banco de dados por meio do listener para verificar a configuração do listener Oracle com o seguinte comando.  Altere para a porta do listener e o nome do serviço de banco de dados apropriados.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 13:19:57 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Wed May 05 2021 17:11:11 -04:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL> show user
USER is "SYSTEM"
SQL> show con_name
CON_NAME
CDB2_PDB1
----
+
Isso confirma que o ouvinte do Oracle está funcionando corretamente.





=== Onde procurar ajuda?

Se precisar de ajuda com o kit de ferramentas, junte-se a nóslink:https://netapppub.slack.com/archives/C021R4WC0LC["Canal do Slack de suporte da comunidade de automação de soluções da NetApp"] e procure o canal de automação de soluções para postar suas dúvidas ou perguntas.
