---
sidebar: sidebar 
permalink: automation/db-protection-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Esta página descreve o método automatizado para implantar o Oracle19c no armazenamento NetApp ONTAP . 
---
= Visão geral da solução
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta página descreve o método automatizado para implantar o Oracle19c no armazenamento NetApp ONTAP .



== Proteção de dados automatizada para bancos de dados Oracle

As organizações estão automatizando seus ambientes para ganhar eficiência, acelerar implantações e reduzir o esforço manual.  Ferramentas de gerenciamento de configuração como o Ansible estão sendo usadas para otimizar as operações de banco de dados corporativo.  Nesta solução, demonstramos como você pode usar o Ansible para automatizar a proteção de dados do Oracle com o NetApp ONTAP.  Ao permitir que administradores de armazenamento, administradores de sistemas e DBAs configurem de forma consistente e rápida a replicação de dados para um data center externo ou para uma nuvem pública, você obtém os seguintes benefícios:

* Elimine complexidades de design e erros humanos e implemente uma implantação consistente e repetível e melhores práticas
* Reduza o tempo de configuração de replicação Intercluster, instanciação de CVO e recuperação de bancos de dados Oracle
* Aumentar a produtividade dos administradores de banco de dados, sistemas e armazenamento
* Fornece fluxo de trabalho de recuperação de banco de dados para facilitar o teste de um cenário de DR.


A NetApp fornece aos clientes módulos e funções Ansible validados para acelerar a implantação, a configuração e o gerenciamento do ciclo de vida do seu ambiente de banco de dados Oracle.  Esta solução fornece instruções e código de manual do Ansible para ajudar você a:



=== Replicação local para local

* Crie vidas intercluster na origem e no destino
* Estabelecer peering de cluster e vserver
* Criar e inicializar o SnapMirror de volumes Oracle
* Crie um cronograma de replicação por meio do AWX/Tower para binários, bancos de dados e logs Oracle
* Restaurar o Oracle DB no destino e colocar o banco de dados online




=== On Prem para CVO na AWS

* Criar conector AWS
* Criar instância CVO na AWS
* Adicionar cluster local ao Cloud Manager
* Criar vidas intercluster na fonte
* Estabelecer peering de cluster e vserver
* Criar e inicializar o SnapMirror de volumes Oracle
* Crie um cronograma de replicação por meio do AWX/Tower para binários, bancos de dados e logs Oracle
* Restaurar o Oracle DB no destino e colocar o banco de dados online


Depois que estiver pronto, cliquelink:db-protection-getting-started.html["aqui para começar com a solução"] .
