---
sidebar: sidebar 
permalink: automation/marketing-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Esta página descreve o método automatizado para implantar o Oracle19c no armazenamento NetApp ONTAP . 
---
= Visão geral da solução
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta página descreve o método automatizado para implantar o Oracle19c no armazenamento NetApp ONTAP .



== Implantação automatizada do Oracle19c para ONTAP no NFS

As organizações estão automatizando seus ambientes para ganhar eficiência, acelerar implantações e reduzir o esforço manual.  Ferramentas de gerenciamento de configuração como o Ansible estão sendo usadas para otimizar as operações de banco de dados corporativo.  Nesta solução, demonstramos como você pode usar o Ansible para automatizar o provisionamento e a configuração do Oracle 19c com o NetApp ONTAP.  Ao permitir que administradores de armazenamento, administradores de sistemas e DBAs implantem de forma consistente e rápida novos armazenamentos, configurem servidores de banco de dados e instalem o software Oracle 19c, você obtém os seguintes benefícios:

* Elimine complexidades de design e erros humanos e implemente uma implantação consistente e repetível e melhores práticas
* Diminua o tempo de provisionamento de armazenamento, configuração de hosts de banco de dados e instalação do Oracle
* Aumentar a produtividade dos administradores de banco de dados, sistemas e armazenamento
* Habilite o dimensionamento de armazenamento e bancos de dados com facilidade


A NetApp fornece aos clientes módulos e funções Ansible validados para acelerar a implantação, a configuração e o gerenciamento do ciclo de vida do seu ambiente de banco de dados Oracle.  Esta solução fornece instruções e código de manual do Ansible para ajudar você a:

* Criar e configurar o armazenamento ONTAP NFS para o Oracle Database
* Instalar o Oracle 19c no RedHat Enterprise Linux 7/8 ou Oracle Linux 7/8
* Configurar o Oracle 19c no armazenamento ONTAP NFS


Para mais detalhes ou para começar, assista aos vídeos de visão geral abaixo.



=== Implantações AWX/Torre

Parte 1: Introdução, Requisitos, Detalhes de Automação e Configuração Inicial do AWX/Torre

.Implantação AWX
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
Parte 2: Variáveis e execução do manual

.Execução do Manual de Jogadas AWX
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


=== Implantação CLI

Parte 1: Introdução, Requisitos, Detalhes de Automação e Configuração do Host de Controle Ansible

.Implantação CLI
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
Parte 2: Variáveis e execução do manual

.Execução do manual CLI
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]